/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#include "blowfish_dot_c_test.h"

#include "gtest/gtest.h"

namespace UTBot {
// Tests for F were not generated. Maybe the function is too complex.

// Tests for Blowfish_Encrypt were not generated. Maybe the function is too complex.

// Tests for Blowfish_Decrypt were not generated. Maybe the function is too complex.

// Tests for Blowfish_Init were not generated. Maybe the function is too complex.



}
