/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#include "keys_dot_c_test.h"

#include "gtest/gtest.h"

namespace UTBot {


#pragma region regression
TEST(regression, getkey_test1)
{
    EXPECT_TRUE(getkey(-5) == NULL);
}

#pragma endregion
#pragma region error
// Error: memory error: out of bound pointer
TEST(error, mutateKey_test1)
{
    char _key[2][2] = {{'\0', 'c'}, {'c', 'c'}};
    char ** key = (char **) calloc(3, sizeof(char *));
    for (int it_152_0 = 0; it_152_0 < 2; it_152_0 ++) {
        key[it_152_0] = _key[it_152_0];
    }
    key[2] = NULL;
    char _key2[2][2] = {{'a', 'c'}, {'c', 'c'}};
    char ** key2 = (char **) calloc(3, sizeof(char *));
    for (int it_153_0 = 0; it_153_0 < 2; it_153_0 ++) {
        key2[it_153_0] = _key2[it_153_0];
    }
    key2[2] = NULL;
    mutateKey(key, key2);

    FAIL() << "Unreachable point or the function was supposed to fail, but "
        "actually completed successfully. See the SARIF report for details.";
}

#pragma endregion
}
