/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#define main main__
#include "../../blowfish.c"
#pragma GCC visibility push (default)
typedef const uInt32 (*ORIG_P_pointer)[18];
ORIG_P_pointer get_pointer_to_ORIG_P_blowfish_c() {
return &ORIG_P;
}
typedef const uInt32 (*ORIG_S_pointer)[4][256];
ORIG_S_pointer get_pointer_to_ORIG_S_blowfish_c() {
return &ORIG_S;
}
uInt32 F_blowfish_c(BLOWFISH_CTX *ctx, uInt32 x) {
return F(ctx, x);
}
void Blowfish_Encrypt_blowfish_c(BLOWFISH_CTX *ctx, uInt32 *xl, uInt32 *xr) {
Blowfish_Encrypt(ctx, xl, xr);
}
void Blowfish_Decrypt_blowfish_c(BLOWFISH_CTX *ctx, uInt32 *xl, uInt32 *xr) {
Blowfish_Decrypt(ctx, xl, xr);
}
void Blowfish_Init_blowfish_c(BLOWFISH_CTX *ctx, unsigned char *key, int keyLen) {
Blowfish_Init(ctx, key, keyLen);
}
#pragma GCC visibility pop
