/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#define main main__
#include "../../endian.c"
#pragma GCC visibility push (default)
void getEndian_endian_c(unsigned char **e) {
getEndian(e);
}
uInt32 swapEndian_endian_c(uInt32 value) {
return swapEndian(value);
}
int testEndian_endian_c(char *input) {
return testEndian(input);
}
int swapCompressed_endian_c(char **input, uLong sz) {
return swapCompressed(input, sz);
}
#pragma GCC visibility pop
