/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#define main main__
#include "../../keys.c"
#pragma GCC visibility push (default)
char *getkey_keys_c(int type) {
return getkey(type);
}
void mutateKey_keys_c(char **key, char **key2) {
mutateKey(key, key2);
}
#pragma GCC visibility pop
