/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#define main main__
#include "../../rwfile.c"
#pragma GCC visibility push (default)
int getremain_rwfile_c(uLong sz, int dv) {
return getremain(sz, dv);
}
uLong padInput_rwfile_c(char **input, uLong sz) {
return padInput(input, sz);
}
uLong attachKey_rwfile_c(char **input, char *key, uLong sz) {
return attachKey(input, key, sz);
}
uLong readfile_rwfile_c(char *infile, char **input, int type, char *key, struct stat statbuf) {
return readfile(infile, input, type, key, statbuf);
}
uLong writefile_rwfile_c(char *outfile, char *output, uLong sz, BCoptions options, struct stat statbuf) {
return writefile(outfile, output, sz, options, statbuf);
}
int deletefile_rwfile_c(char *file, BCoptions options, char *key, struct stat statbuf) {
return deletefile(file, options, key, statbuf);
}
#pragma GCC visibility pop
