/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#define main main__
#include "../../wrapzl.c"
#pragma GCC visibility push (default)
uLong docompress_wrapzl_c(char **input, uLong sz) {
return docompress(input, sz);
}
uLong douncompress_wrapzl_c(char **input, uLong sz, BCoptions options) {
return douncompress(input, sz, options);
}
#pragma GCC visibility pop
