/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#define main main__
#include "../../wrapbf.c"
#pragma GCC visibility push (default)
uLong BFEncrypt_wrapbf_c(char **input, char *key, uLong sz, BCoptions *options) {
return BFEncrypt(input, key, sz, options);
}
uLong BFDecrypt_wrapbf_c(char **input, char *key, char *key2, uLong sz, BCoptions *options) {
return BFDecrypt(input, key, key2, sz, options);
}
#pragma GCC visibility pop
