// 1720683636000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "endian_stub.h"

#pragma GCC visibility push (default)
#define NULL ((void*)0)

void getEndian(unsigned char ** e) {
    return;
}


unsigned int swapEndian_symbolic[10];
unsigned int swapEndian(uInt32 value) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&swapEndian_symbolic, sizeof(swapEndian_symbolic), "swapEndian_symbolic");
            for (int it_5_0 = 0; it_5_0 < 10; it_5_0 ++) {
                klee_prefer_cex(swapEndian_symbolic, swapEndian_symbolic[it_5_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return swapEndian_symbolic[cntCall++];
}


int testEndian_symbolic[10];
int testEndian(char * input) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&testEndian_symbolic, sizeof(testEndian_symbolic), "testEndian_symbolic");
            for (int it_6_0 = 0; it_6_0 < 10; it_6_0 ++) {
                klee_prefer_cex(testEndian_symbolic, testEndian_symbolic[it_6_0] >= -10 & testEndian_symbolic[it_6_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return testEndian_symbolic[cntCall++];
}


int swapCompressed_symbolic[10];
int swapCompressed(char ** input, uLong sz) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&swapCompressed_symbolic, sizeof(swapCompressed_symbolic), "swapCompressed_symbolic");
            for (int it_7_0 = 0; it_7_0 < 10; it_7_0 ++) {
                klee_prefer_cex(swapCompressed_symbolic, swapCompressed_symbolic[it_7_0] >= -10 & swapCompressed_symbolic[it_7_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return swapCompressed_symbolic[cntCall++];
}


#pragma GCC visibility pop
