// 1720683636000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "keys_stub.h"

#pragma GCC visibility push (default)
#define NULL ((void*)0)

char * getkey(int type) {
    return "";
}


void mutateKey(char ** key, char ** key2) {
    return;
}


#pragma GCC visibility pop
