// 1720683636000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "main_stub.h"

#pragma GCC visibility push (default)
#define NULL ((void*)0)

struct _BCoptions initoptions_symbolic[10];
struct _BCoptions initoptions(BCoptions options) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&initoptions_symbolic, sizeof(initoptions_symbolic), "initoptions_symbolic");
            for (int it_15_0 = 0; it_15_0 < 10; it_15_0 ++) {
                // No constraints for initoptions_symbolic[it_15_0]
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return initoptions_symbolic[cntCall++];
}


int usage_symbolic[10];
int usage(char * name) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&usage_symbolic, sizeof(usage_symbolic), "usage_symbolic");
            for (int it_16_0 = 0; it_16_0 < 10; it_16_0 ++) {
                klee_prefer_cex(usage_symbolic, usage_symbolic[it_16_0] >= -10 & usage_symbolic[it_16_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return usage_symbolic[cntCall++];
}


int memerror_symbolic[10];
int memerror() {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&memerror_symbolic, sizeof(memerror_symbolic), "memerror_symbolic");
            for (int it_17_0 = 0; it_17_0 < 10; it_17_0 ++) {
                klee_prefer_cex(memerror_symbolic, memerror_symbolic[it_17_0] >= -10 & memerror_symbolic[it_17_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return memerror_symbolic[cntCall++];
}


int parseArgs_symbolic[10];
int parseArgs(int * argc, char ** argv, BCoptions * options) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&parseArgs_symbolic, sizeof(parseArgs_symbolic), "parseArgs_symbolic");
            for (int it_18_0 = 0; it_18_0 < 10; it_18_0 ++) {
                klee_prefer_cex(parseArgs_symbolic, parseArgs_symbolic[it_18_0] >= -10 & parseArgs_symbolic[it_18_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return parseArgs_symbolic[cntCall++];
}


int assignFiles_symbolic[10];
int assignFiles(char * arg, char ** infile, char ** outfile, struct stat * statbuf, BCoptions * options, char * key) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&assignFiles_symbolic, sizeof(assignFiles_symbolic), "assignFiles_symbolic");
            for (int it_19_0 = 0; it_19_0 < 10; it_19_0 ++) {
                klee_prefer_cex(assignFiles_symbolic, assignFiles_symbolic[it_19_0] >= -10 & assignFiles_symbolic[it_19_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return assignFiles_symbolic[cntCall++];
}


int main_symbolic[10];
int main(int argc, char ** argv) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&main_symbolic, sizeof(main_symbolic), "main_symbolic");
            for (int it_20_0 = 0; it_20_0 < 10; it_20_0 ++) {
                klee_prefer_cex(main_symbolic, main_symbolic[it_20_0] >= -10 & main_symbolic[it_20_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return main_symbolic[cntCall++];
}


#pragma GCC visibility pop
