// 1720683636000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "rwfile_stub.h"

#pragma GCC visibility push (default)
#define NULL ((void*)0)

int getremain_symbolic[10];
int getremain(uLong sz, int dv) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&getremain_symbolic, sizeof(getremain_symbolic), "getremain_symbolic");
            for (int it_9_0 = 0; it_9_0 < 10; it_9_0 ++) {
                klee_prefer_cex(getremain_symbolic, getremain_symbolic[it_9_0] >= -10 & getremain_symbolic[it_9_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return getremain_symbolic[cntCall++];
}


unsigned long padInput_symbolic[10];
unsigned long padInput(char ** input, uLong sz) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&padInput_symbolic, sizeof(padInput_symbolic), "padInput_symbolic");
            for (int it_10_0 = 0; it_10_0 < 10; it_10_0 ++) {
                klee_prefer_cex(padInput_symbolic, padInput_symbolic[it_10_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return padInput_symbolic[cntCall++];
}


unsigned long attachKey_symbolic[10];
unsigned long attachKey(char ** input, char * key, uLong sz) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&attachKey_symbolic, sizeof(attachKey_symbolic), "attachKey_symbolic");
            for (int it_11_0 = 0; it_11_0 < 10; it_11_0 ++) {
                klee_prefer_cex(attachKey_symbolic, attachKey_symbolic[it_11_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return attachKey_symbolic[cntCall++];
}


unsigned long readfile_symbolic[10];
unsigned long readfile(char * infile, char ** input, int type, char * key, struct stat statbuf) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&readfile_symbolic, sizeof(readfile_symbolic), "readfile_symbolic");
            for (int it_12_0 = 0; it_12_0 < 10; it_12_0 ++) {
                klee_prefer_cex(readfile_symbolic, readfile_symbolic[it_12_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return readfile_symbolic[cntCall++];
}


unsigned long writefile_symbolic[10];
unsigned long writefile(char * outfile, char * output, uLong sz, BCoptions options, struct stat statbuf) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&writefile_symbolic, sizeof(writefile_symbolic), "writefile_symbolic");
            for (int it_13_0 = 0; it_13_0 < 10; it_13_0 ++) {
                klee_prefer_cex(writefile_symbolic, writefile_symbolic[it_13_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return writefile_symbolic[cntCall++];
}


int deletefile_symbolic[10];
int deletefile(char * file, BCoptions options, char * key, struct stat statbuf) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&deletefile_symbolic, sizeof(deletefile_symbolic), "deletefile_symbolic");
            for (int it_14_0 = 0; it_14_0 < 10; it_14_0 ++) {
                klee_prefer_cex(deletefile_symbolic, deletefile_symbolic[it_14_0] >= -10 & deletefile_symbolic[it_14_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return deletefile_symbolic[cntCall++];
}


#pragma GCC visibility pop
