// 1720683636000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "wrapzl_stub.h"

#pragma GCC visibility push (default)
#define NULL ((void*)0)

unsigned long docompress_symbolic[10];
unsigned long docompress(char ** input, uLong sz) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&docompress_symbolic, sizeof(docompress_symbolic), "docompress_symbolic");
            for (int it_1_0 = 0; it_1_0 < 10; it_1_0 ++) {
                klee_prefer_cex(docompress_symbolic, docompress_symbolic[it_1_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return docompress_symbolic[cntCall++];
}


unsigned long douncompress_symbolic[10];
unsigned long douncompress(char ** input, uLong sz, BCoptions options) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&douncompress_symbolic, sizeof(douncompress_symbolic), "douncompress_symbolic");
            for (int it_2_0 = 0; it_2_0 < 10; it_2_0 ++) {
                klee_prefer_cex(douncompress_symbolic, douncompress_symbolic[it_2_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return douncompress_symbolic[cntCall++];
}


#pragma GCC visibility pop
