// 1720683636000000000
// Please, do not change the line above

/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#ifdef KLEE_MODE
extern void klee_make_symbolic(void *addr, unsigned long long nbytes, const char *name);
#endif
#include "wrapbf_stub.h"

#pragma GCC visibility push (default)
#define NULL ((void*)0)

unsigned long BFEncrypt_symbolic[10];
unsigned long BFEncrypt(char ** input, char * key, uLong sz, BCoptions * options) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&BFEncrypt_symbolic, sizeof(BFEncrypt_symbolic), "BFEncrypt_symbolic");
            for (int it_3_0 = 0; it_3_0 < 10; it_3_0 ++) {
                klee_prefer_cex(BFEncrypt_symbolic, BFEncrypt_symbolic[it_3_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return BFEncrypt_symbolic[cntCall++];
}


unsigned long BFDecrypt_symbolic[10];
unsigned long BFDecrypt(char ** input, char * key, char * key2, uLong sz, BCoptions * options) {
    static int firstTimeCall = 1;
    static int cntCall = 0;
    #ifdef KLEE_MODE
        if (firstTimeCall == 1) {
            firstTimeCall = 0;
            klee_make_symbolic(&BFDecrypt_symbolic, sizeof(BFDecrypt_symbolic), "BFDecrypt_symbolic");
            for (int it_4_0 = 0; it_4_0 < 10; it_4_0 ++) {
                klee_prefer_cex(BFDecrypt_symbolic, BFDecrypt_symbolic[it_4_0] <= 10);
            }
        }
    #endif
    if (cntCall == 10) {
        cntCall--;
    }
    return BFDecrypt_symbolic[cntCall++];
}


#pragma GCC visibility pop
